### ISSUE TITLE
Custom config settings don't seem to be picked up consistently

### ISSUE THREAD

**Issue by KarlBishop** [putyourlightson/craft-blitz#330]
I have copied the example config file to ./config/blitz.php so I can use custom settings per environment.

In my config I have settings like:
```
<?php
return [
    '*' => [
        'cachingEnabled' => true,
    ],
    'dev' => [
        'cachingEnabled' => false,
    ],
    'production' => [
        'queryStringCaching' => 2,
        'sendPoweredByHeader' => false,
        ...
    ]
];
```

However, when I look in the CP under **Utilities>Project Config>Loaded Project Config Data** my custom settings aren't reflected.

In both dev and production environments I see the same:

```
  blitz:
    edition: standard
    enabled: true
    licenseKey: ##########
    schemaVersion: 3.6.6
    settings:
      apiKey: ''
      cachingEnabled: ''
      queryStringCaching: '0'
      sendPoweredByHeader: true
      ...
```

Shouldn't I be seeing `cachingEnabled: true`, `queryStringCaching: '2'` and `sendPoweredByHeader: false` in production?

### Additionally

- In dev under **Settings>Blitz>Caching Enabled** I can see the message "This is being overridden by the cachingEnabled config setting" so the custom file seems to be picked up there.
- I cannot see the powered by header in production even when I set `'sendPoweredByHeader' => true` in my config file, and even after running `php craft project-config/apply --force`. Yet I do see the powered by header in dev when I turn caching on there. And I do see in production under **Utilities>Blitz Cache** that the number of Cached Pages goes up when I visit pages on the site.

### Versions
- Plugin version: 3.9.0
- Craft version: Craft Pro 3.6.16
